package eam.desarrollo.entidades;

import java.io.Serializable;
import java.sql.Blob;

/**
 * Model class of control_hospitalizacion.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ControlHospitalizacion implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_control_hospitalizacion. */
	private Blob idControlHospitalizacion;

	/** hospitalizacion. */
	private Hospitalizacion hospitalizacion;

	/** procedimiento. */
	private Procedimiento procedimiento;

	/**
	 * Constructor.
	 */
	public ControlHospitalizacion() {
	}

	/**
	 * Set the id_control_hospitalizacion.
	 * 
	 * @param idControlHospitalizacion
	 *            id_control_hospitalizacion
	 */
	public void setIdControlHospitalizacion(Blob idControlHospitalizacion) {
		this.idControlHospitalizacion = idControlHospitalizacion;
	}

	/**
	 * Get the id_control_hospitalizacion.
	 * 
	 * @return id_control_hospitalizacion
	 */
	public Blob getIdControlHospitalizacion() {
		return this.idControlHospitalizacion;
	}

	/**
	 * Set the hospitalizacion.
	 * 
	 * @param hospitalizacion
	 *            hospitalizacion
	 */
	public void setHospitalizacion(Hospitalizacion hospitalizacion) {
		this.hospitalizacion = hospitalizacion;
	}

	/**
	 * Get the hospitalizacion.
	 * 
	 * @return hospitalizacion
	 */
	public Hospitalizacion getHospitalizacion() {
		return this.hospitalizacion;
	}

	/**
	 * Set the procedimiento.
	 * 
	 * @param procedimiento
	 *            procedimiento
	 */
	public void setProcedimiento(Procedimiento procedimiento) {
		this.procedimiento = procedimiento;
	}

	/**
	 * Get the procedimiento.
	 * 
	 * @return procedimiento
	 */
	public Procedimiento getProcedimiento() {
		return this.procedimiento;
	}


}
