package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of departamento.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Departamento implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_departamento. */
	private String idDepartamento;

	/** nombre_departamento. */
	private String nombreDepartamento;

	/** The set of municipio. */
	private Set<Municipio> municipioSet;

	/**
	 * Constructor.
	 */
	public Departamento() {
		this.municipioSet = new HashSet<Municipio>();
	}

	/**
	 * Set the id_departamento.
	 * 
	 * @param idDepartamento
	 *            id_departamento
	 */
	public void setIdDepartamento(String idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	/**
	 * Get the id_departamento.
	 * 
	 * @return id_departamento
	 */
	public String getIdDepartamento() {
		return this.idDepartamento;
	}

	/**
	 * Set the nombre_departamento.
	 * 
	 * @param nombreDepartamento
	 *            nombre_departamento
	 */
	public void setNombreDepartamento(String nombreDepartamento) {
		this.nombreDepartamento = nombreDepartamento;
	}

	/**
	 * Get the nombre_departamento.
	 * 
	 * @return nombre_departamento
	 */
	public String getNombreDepartamento() {
		return this.nombreDepartamento;
	}

	/**
	 * Set the set of the municipio.
	 * 
	 * @param municipioSet
	 *            The set of municipio
	 */
	public void setMunicipioSet(Set<Municipio> municipioSet) {
		this.municipioSet = municipioSet;
	}

	/**
	 * Add the municipio.
	 * 
	 * @param municipio
	 *            municipio
	 */
	public void addMunicipio(Municipio municipio) {
		this.municipioSet.add(municipio);
	}

	/**
	 * Get the set of the municipio.
	 * 
	 * @return The set of municipio
	 */
	public Set<Municipio> getMunicipioSet() {
		return this.municipioSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idDepartamento == null) ? 0 : idDepartamento.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Departamento other = (Departamento) obj;
		if (idDepartamento == null) {
			if (other.idDepartamento != null) {
				return false;
			}
		} else if (!idDepartamento.equals(other.idDepartamento)) {
			return false;
		}
		return true;
	}

}
