package eam.desarrollo.entidades;

import java.io.Serializable;
import java.sql.Time;
import java.util.Date;

/**
 * Model class of entrada_medico.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EntradaMedico implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_entrada_medico. */
	private String idEntradaMedico;

	/** fecha_entrada_medico. */
	private Date fechaEntradaMedico;

	/** hora_entrada_medico. */
	private Time horaEntradaMedico;

	/** medico. */
	private Medico medico;

	/**
	 * Constructor.
	 */
	public EntradaMedico() {
	}

	/**
	 * Set the id_entrada_medico.
	 * 
	 * @param idEntradaMedico
	 *            id_entrada_medico
	 */
	public void setIdEntradaMedico(String idEntradaMedico) {
		this.idEntradaMedico = idEntradaMedico;
	}

	/**
	 * Get the id_entrada_medico.
	 * 
	 * @return id_entrada_medico
	 */
	public String getIdEntradaMedico() {
		return this.idEntradaMedico;
	}

	/**
	 * Set the fecha_entrada_medico.
	 * 
	 * @param fechaEntradaMedico
	 *            fecha_entrada_medico
	 */
	public void setFechaEntradaMedico(Date fechaEntradaMedico) {
		this.fechaEntradaMedico = fechaEntradaMedico;
	}

	/**
	 * Get the fecha_entrada_medico.
	 * 
	 * @return fecha_entrada_medico
	 */
	public Date getFechaEntradaMedico() {
		return this.fechaEntradaMedico;
	}

	/**
	 * Set the hora_entrada_medico.
	 * 
	 * @param horaEntradaMedico
	 *            hora_entrada_medico
	 */
	public void setHoraEntradaMedico(Time horaEntradaMedico) {
		this.horaEntradaMedico = horaEntradaMedico;
	}

	/**
	 * Get the hora_entrada_medico.
	 * 
	 * @return hora_entrada_medico
	 */
	public Time getHoraEntradaMedico() {
		return this.horaEntradaMedico;
	}

	/**
	 * Set the medico.
	 * 
	 * @param medico
	 *            medico
	 */
	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	/**
	 * Get the medico.
	 * 
	 * @return medico
	 */
	public Medico getMedico() {
		return this.medico;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEntradaMedico == null) ? 0 : idEntradaMedico.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EntradaMedico other = (EntradaMedico) obj;
		if (idEntradaMedico == null) {
			if (other.idEntradaMedico != null) {
				return false;
			}
		} else if (!idEntradaMedico.equals(other.idEntradaMedico)) {
			return false;
		}
		return true;
	}

}
