package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of especialidad.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Especialidad implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_especialidad. */
	private String idEspecialidad;

	/** descripcion_especialidad. */
	private String descripcionEspecialidad;

	/** incapacidad. */
	private Incapacidad incapacidad;

	/**
	 * Constructor.
	 */
	public Especialidad() {
	}

	/**
	 * Set the id_especialidad.
	 * 
	 * @param idEspecialidad
	 *            id_especialidad
	 */
	public void setIdEspecialidad(String idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	/**
	 * Get the id_especialidad.
	 * 
	 * @return id_especialidad
	 */
	public String getIdEspecialidad() {
		return this.idEspecialidad;
	}

	/**
	 * Set the descripcion_especialidad.
	 * 
	 * @param descripcionEspecialidad
	 *            descripcion_especialidad
	 */
	public void setDescripcionEspecialidad(String descripcionEspecialidad) {
		this.descripcionEspecialidad = descripcionEspecialidad;
	}

	/**
	 * Get the descripcion_especialidad.
	 * 
	 * @return descripcion_especialidad
	 */
	public String getDescripcionEspecialidad() {
		return this.descripcionEspecialidad;
	}

	/**
	 * Set the incapacidad.
	 * 
	 * @param incapacidad
	 *            incapacidad
	 */
	public void setIncapacidad(Incapacidad incapacidad) {
		this.incapacidad = incapacidad;
	}

	/**
	 * Get the incapacidad.
	 * 
	 * @return incapacidad
	 */
	public Incapacidad getIncapacidad() {
		return this.incapacidad;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEspecialidad == null) ? 0 : idEspecialidad.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Especialidad other = (Especialidad) obj;
		if (idEspecialidad == null) {
			if (other.idEspecialidad != null) {
				return false;
			}
		} else if (!idEspecialidad.equals(other.idEspecialidad)) {
			return false;
		}
		return true;
	}

}
