package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of estado_hospitalizacion.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EstadoHospitalizacion implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_estado_hospitalizacion. */
	private String idEstadoHospitalizacion;

	/** descripcion_estado_hospitalizacion. */
	private String descripcionEstadoHospitalizacion;

	/** The set of hospitalizacion. */
	private Set<Hospitalizacion> hospitalizacionSet;

	/**
	 * Constructor.
	 */
	public EstadoHospitalizacion() {
		this.hospitalizacionSet = new HashSet<Hospitalizacion>();
	}

	/**
	 * Set the id_estado_hospitalizacion.
	 * 
	 * @param idEstadoHospitalizacion
	 *            id_estado_hospitalizacion
	 */
	public void setIdEstadoHospitalizacion(String idEstadoHospitalizacion) {
		this.idEstadoHospitalizacion = idEstadoHospitalizacion;
	}

	/**
	 * Get the id_estado_hospitalizacion.
	 * 
	 * @return id_estado_hospitalizacion
	 */
	public String getIdEstadoHospitalizacion() {
		return this.idEstadoHospitalizacion;
	}

	/**
	 * Set the descripcion_estado_hospitalizacion.
	 * 
	 * @param descripcionEstadoHospitalizacion
	 *            descripcion_estado_hospitalizacion
	 */
	public void setDescripcionEstadoHospitalizacion(String descripcionEstadoHospitalizacion) {
		this.descripcionEstadoHospitalizacion = descripcionEstadoHospitalizacion;
	}

	/**
	 * Get the descripcion_estado_hospitalizacion.
	 * 
	 * @return descripcion_estado_hospitalizacion
	 */
	public String getDescripcionEstadoHospitalizacion() {
		return this.descripcionEstadoHospitalizacion;
	}

	/**
	 * Set the set of the hospitalizacion.
	 * 
	 * @param hospitalizacionSet
	 *            The set of hospitalizacion
	 */
	public void setHospitalizacionSet(Set<Hospitalizacion> hospitalizacionSet) {
		this.hospitalizacionSet = hospitalizacionSet;
	}

	/**
	 * Add the hospitalizacion.
	 * 
	 * @param hospitalizacion
	 *            hospitalizacion
	 */
	public void addHospitalizacion(Hospitalizacion hospitalizacion) {
		this.hospitalizacionSet.add(hospitalizacion);
	}

	/**
	 * Get the set of the hospitalizacion.
	 * 
	 * @return The set of hospitalizacion
	 */
	public Set<Hospitalizacion> getHospitalizacionSet() {
		return this.hospitalizacionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEstadoHospitalizacion == null) ? 0 : idEstadoHospitalizacion.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EstadoHospitalizacion other = (EstadoHospitalizacion) obj;
		if (idEstadoHospitalizacion == null) {
			if (other.idEstadoHospitalizacion != null) {
				return false;
			}
		} else if (!idEstadoHospitalizacion.equals(other.idEstadoHospitalizacion)) {
			return false;
		}
		return true;
	}

}
