package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of estado_consultorio.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EstadoConsultorio implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_estado_consultorio. */
	private String idEstadoConsultorio;

	/** descripcion_estado_consultorio. */
	private String descripcionEstadoConsultorio;

	/** The set of consultorio. */
	private Set<Consultorio> consultorioSet;

	/**
	 * Constructor.
	 */
	public EstadoConsultorio() {
		this.consultorioSet = new HashSet<Consultorio>();
	}

	/**
	 * Set the id_estado_consultorio.
	 * 
	 * @param idEstadoConsultorio
	 *            id_estado_consultorio
	 */
	public void setIdEstadoConsultorio(String idEstadoConsultorio) {
		this.idEstadoConsultorio = idEstadoConsultorio;
	}

	/**
	 * Get the id_estado_consultorio.
	 * 
	 * @return id_estado_consultorio
	 */
	public String getIdEstadoConsultorio() {
		return this.idEstadoConsultorio;
	}

	/**
	 * Set the descripcion_estado_consultorio.
	 * 
	 * @param descripcionEstadoConsultorio
	 *            descripcion_estado_consultorio
	 */
	public void setDescripcionEstadoConsultorio(String descripcionEstadoConsultorio) {
		this.descripcionEstadoConsultorio = descripcionEstadoConsultorio;
	}

	/**
	 * Get the descripcion_estado_consultorio.
	 * 
	 * @return descripcion_estado_consultorio
	 */
	public String getDescripcionEstadoConsultorio() {
		return this.descripcionEstadoConsultorio;
	}

	/**
	 * Set the set of the consultorio.
	 * 
	 * @param consultorioSet
	 *            The set of consultorio
	 */
	public void setConsultorioSet(Set<Consultorio> consultorioSet) {
		this.consultorioSet = consultorioSet;
	}

	/**
	 * Add the consultorio.
	 * 
	 * @param consultorio
	 *            consultorio
	 */
	public void addConsultorio(Consultorio consultorio) {
		this.consultorioSet.add(consultorio);
	}

	/**
	 * Get the set of the consultorio.
	 * 
	 * @return The set of consultorio
	 */
	public Set<Consultorio> getConsultorioSet() {
		return this.consultorioSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEstadoConsultorio == null) ? 0 : idEstadoConsultorio.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EstadoConsultorio other = (EstadoConsultorio) obj;
		if (idEstadoConsultorio == null) {
			if (other.idEstadoConsultorio != null) {
				return false;
			}
		} else if (!idEstadoConsultorio.equals(other.idEstadoConsultorio)) {
			return false;
		}
		return true;
	}

}
