package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of formula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Formula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_formula. */
	private String idFormula;

	/** medico. */
	private Medico medico;

	/** The set of formula_medicamento. */
	private Set<FormulaMedicamento> formulaMedicamentoSet;

	/**
	 * Constructor.
	 */
	public Formula() {
		this.formulaMedicamentoSet = new HashSet<FormulaMedicamento>();
	}

	/**
	 * Set the id_formula.
	 * 
	 * @param idFormula
	 *            id_formula
	 */
	public void setIdFormula(String idFormula) {
		this.idFormula = idFormula;
	}

	/**
	 * Get the id_formula.
	 * 
	 * @return id_formula
	 */
	public String getIdFormula() {
		return this.idFormula;
	}

	/**
	 * Set the medico.
	 * 
	 * @param medico
	 *            medico
	 */
	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	/**
	 * Get the medico.
	 * 
	 * @return medico
	 */
	public Medico getMedico() {
		return this.medico;
	}

	/**
	 * Set the set of the formula_medicamento.
	 * 
	 * @param formulaMedicamentoSet
	 *            The set of formula_medicamento
	 */
	public void setFormulaMedicamentoSet(Set<FormulaMedicamento> formulaMedicamentoSet) {
		this.formulaMedicamentoSet = formulaMedicamentoSet;
	}

	/**
	 * Add the formula_medicamento.
	 * 
	 * @param formulaMedicamento
	 *            formula_medicamento
	 */
	public void addFormulaMedicamento(FormulaMedicamento formulaMedicamento) {
		this.formulaMedicamentoSet.add(formulaMedicamento);
	}

	/**
	 * Get the set of the formula_medicamento.
	 * 
	 * @return The set of formula_medicamento
	 */
	public Set<FormulaMedicamento> getFormulaMedicamentoSet() {
		return this.formulaMedicamentoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idFormula == null) ? 0 : idFormula.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Formula other = (Formula) obj;
		if (idFormula == null) {
			if (other.idFormula != null) {
				return false;
			}
		} else if (!idFormula.equals(other.idFormula)) {
			return false;
		}
		return true;
	}

}
