package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of formula_medicamento.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FormulaMedicamento implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** formula. */
	private Formula formula;

	/** medicamento. */
	private Medicamento medicamento;

	/** cantidad_medicamento_formula. */
	private Integer cantidadMedicamentoFormula;

	/**
	 * Constructor.
	 */
	public FormulaMedicamento() {
	}

	/**
	 * Set the formula.
	 * 
	 * @param formula
	 *            formula
	 */
	public void setFormula(Formula formula) {
		this.formula = formula;
	}

	/**
	 * Get the formula.
	 * 
	 * @return formula
	 */
	public Formula getFormula() {
		return this.formula;
	}

	/**
	 * Set the medicamento.
	 * 
	 * @param medicamento
	 *            medicamento
	 */
	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	/**
	 * Get the medicamento.
	 * 
	 * @return medicamento
	 */
	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	/**
	 * Set the cantidad_medicamento_formula.
	 * 
	 * @param cantidadMedicamentoFormula
	 *            cantidad_medicamento_formula
	 */
	public void setCantidadMedicamentoFormula(Integer cantidadMedicamentoFormula) {
		this.cantidadMedicamentoFormula = cantidadMedicamentoFormula;
	}

	/**
	 * Get the cantidad_medicamento_formula.
	 * 
	 * @return cantidad_medicamento_formula
	 */
	public Integer getCantidadMedicamentoFormula() {
		return this.cantidadMedicamentoFormula;
	}


}
