package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of genero.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Genero implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_genero. */
	private String idGenero;

	/** tipo. */
	private String tipo;

	/** The set of paciente. */
	private Set<Paciente> pacienteSet;

	/**
	 * Constructor.
	 */
	public Genero() {
		this.pacienteSet = new HashSet<Paciente>();
	}

	/**
	 * Set the id_genero.
	 * 
	 * @param idGenero
	 *            id_genero
	 */
	public void setIdGenero(String idGenero) {
		this.idGenero = idGenero;
	}

	/**
	 * Get the id_genero.
	 * 
	 * @return id_genero
	 */
	public String getIdGenero() {
		return this.idGenero;
	}

	/**
	 * Set the tipo.
	 * 
	 * @param tipo
	 *            tipo
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * Get the tipo.
	 * 
	 * @return tipo
	 */
	public String getTipo() {
		return this.tipo;
	}

	/**
	 * Set the set of the paciente.
	 * 
	 * @param pacienteSet
	 *            The set of paciente
	 */
	public void setPacienteSet(Set<Paciente> pacienteSet) {
		this.pacienteSet = pacienteSet;
	}

	/**
	 * Add the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void addPaciente(Paciente paciente) {
		this.pacienteSet.add(paciente);
	}

	/**
	 * Get the set of the paciente.
	 * 
	 * @return The set of paciente
	 */
	public Set<Paciente> getPacienteSet() {
		return this.pacienteSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idGenero == null) ? 0 : idGenero.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Genero other = (Genero) obj;
		if (idGenero == null) {
			if (other.idGenero != null) {
				return false;
			}
		} else if (!idGenero.equals(other.idGenero)) {
			return false;
		}
		return true;
	}

}
