package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of historia.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Historia implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_historia. */
	private String idHistoria;

	/** cita. */
	private Cita cita;

	/** historia_paciente. */
	private HistoriaPaciente historiaPaciente;

	/**
	 * Constructor.
	 */
	public Historia() {
	}

	/**
	 * Set the id_historia.
	 * 
	 * @param idHistoria
	 *            id_historia
	 */
	public void setIdHistoria(String idHistoria) {
		this.idHistoria = idHistoria;
	}

	/**
	 * Get the id_historia.
	 * 
	 * @return id_historia
	 */
	public String getIdHistoria() {
		return this.idHistoria;
	}

	/**
	 * Set the cita.
	 * 
	 * @param cita
	 *            cita
	 */
	public void setCita(Cita cita) {
		this.cita = cita;
	}

	/**
	 * Get the cita.
	 * 
	 * @return cita
	 */
	public Cita getCita() {
		return this.cita;
	}

	/**
	 * Set the historia_paciente.
	 * 
	 * @param historiaPaciente
	 *            historia_paciente
	 */
	public void setHistoriaPaciente(HistoriaPaciente historiaPaciente) {
		this.historiaPaciente = historiaPaciente;
	}

	/**
	 * Get the historia_paciente.
	 * 
	 * @return historia_paciente
	 */
	public HistoriaPaciente getHistoriaPaciente() {
		return this.historiaPaciente;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idHistoria == null) ? 0 : idHistoria.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Historia other = (Historia) obj;
		if (idHistoria == null) {
			if (other.idHistoria != null) {
				return false;
			}
		} else if (!idHistoria.equals(other.idHistoria)) {
			return false;
		}
		return true;
	}

}
