package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of historia_paciente.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HistoriaPaciente implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_historia_paciente. */
	private String idHistoriaPaciente;

	/** paciente. */
	private Paciente paciente;

	/** The set of historia. */
	private Set<Historia> historiaSet;

	/**
	 * Constructor.
	 */
	public HistoriaPaciente() {
		this.historiaSet = new HashSet<Historia>();
	}

	/**
	 * Set the id_historia_paciente.
	 * 
	 * @param idHistoriaPaciente
	 *            id_historia_paciente
	 */
	public void setIdHistoriaPaciente(String idHistoriaPaciente) {
		this.idHistoriaPaciente = idHistoriaPaciente;
	}

	/**
	 * Get the id_historia_paciente.
	 * 
	 * @return id_historia_paciente
	 */
	public String getIdHistoriaPaciente() {
		return this.idHistoriaPaciente;
	}

	/**
	 * Set the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/**
	 * Get the paciente.
	 * 
	 * @return paciente
	 */
	public Paciente getPaciente() {
		return this.paciente;
	}

	/**
	 * Set the set of the historia.
	 * 
	 * @param historiaSet
	 *            The set of historia
	 */
	public void setHistoriaSet(Set<Historia> historiaSet) {
		this.historiaSet = historiaSet;
	}

	/**
	 * Add the historia.
	 * 
	 * @param historia
	 *            historia
	 */
	public void addHistoria(Historia historia) {
		this.historiaSet.add(historia);
	}

	/**
	 * Get the set of the historia.
	 * 
	 * @return The set of historia
	 */
	public Set<Historia> getHistoriaSet() {
		return this.historiaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idHistoriaPaciente == null) ? 0 : idHistoriaPaciente.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HistoriaPaciente other = (HistoriaPaciente) obj;
		if (idHistoriaPaciente == null) {
			if (other.idHistoriaPaciente != null) {
				return false;
			}
		} else if (!idHistoriaPaciente.equals(other.idHistoriaPaciente)) {
			return false;
		}
		return true;
	}

}
