package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of medicamento_proveedor.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MedicamentoProveedor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_medicamento_proveedor. */
	private String idMedicamentoProveedor;

	/** cantidad_medicamento. */
	private Integer cantidadMedicamento;

	/** lote_medicamento. */
	private String loteMedicamento;

	/** fecha_vencimento. */
	private Date fechaVencimento;

	/** proveedor. */
	private Proveedor proveedor;

	/** medicamento. */
	private Medicamento medicamento;

	/**
	 * Constructor.
	 */
	public MedicamentoProveedor() {
	}

	/**
	 * Set the id_medicamento_proveedor.
	 * 
	 * @param idMedicamentoProveedor
	 *            id_medicamento_proveedor
	 */
	public void setIdMedicamentoProveedor(String idMedicamentoProveedor) {
		this.idMedicamentoProveedor = idMedicamentoProveedor;
	}

	/**
	 * Get the id_medicamento_proveedor.
	 * 
	 * @return id_medicamento_proveedor
	 */
	public String getIdMedicamentoProveedor() {
		return this.idMedicamentoProveedor;
	}

	/**
	 * Set the cantidad_medicamento.
	 * 
	 * @param cantidadMedicamento
	 *            cantidad_medicamento
	 */
	public void setCantidadMedicamento(Integer cantidadMedicamento) {
		this.cantidadMedicamento = cantidadMedicamento;
	}

	/**
	 * Get the cantidad_medicamento.
	 * 
	 * @return cantidad_medicamento
	 */
	public Integer getCantidadMedicamento() {
		return this.cantidadMedicamento;
	}

	/**
	 * Set the lote_medicamento.
	 * 
	 * @param loteMedicamento
	 *            lote_medicamento
	 */
	public void setLoteMedicamento(String loteMedicamento) {
		this.loteMedicamento = loteMedicamento;
	}

	/**
	 * Get the lote_medicamento.
	 * 
	 * @return lote_medicamento
	 */
	public String getLoteMedicamento() {
		return this.loteMedicamento;
	}

	/**
	 * Set the fecha_vencimento.
	 * 
	 * @param fechaVencimento
	 *            fecha_vencimento
	 */
	public void setFechaVencimento(Date fechaVencimento) {
		this.fechaVencimento = fechaVencimento;
	}

	/**
	 * Get the fecha_vencimento.
	 * 
	 * @return fecha_vencimento
	 */
	public Date getFechaVencimento() {
		return this.fechaVencimento;
	}

	/**
	 * Set the proveedor.
	 * 
	 * @param proveedor
	 *            proveedor
	 */
	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	/**
	 * Get the proveedor.
	 * 
	 * @return proveedor
	 */
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	/**
	 * Set the medicamento.
	 * 
	 * @param medicamento
	 *            medicamento
	 */
	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	/**
	 * Get the medicamento.
	 * 
	 * @return medicamento
	 */
	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idMedicamentoProveedor == null) ? 0 : idMedicamentoProveedor.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MedicamentoProveedor other = (MedicamentoProveedor) obj;
		if (idMedicamentoProveedor == null) {
			if (other.idMedicamentoProveedor != null) {
				return false;
			}
		} else if (!idMedicamentoProveedor.equals(other.idMedicamentoProveedor)) {
			return false;
		}
		return true;
	}

}
