package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of municipio.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Municipio implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_municipio. */
	private String idMunicipio;

	/** nombre_municipio. */
	private String nombreMunicipio;

	/** departamento. */
	private Departamento departamento;

	/** The set of paciente. */
	private Set<Paciente> pacienteSet;

	/**
	 * Constructor.
	 */
	public Municipio() {
		this.pacienteSet = new HashSet<Paciente>();
	}

	/**
	 * Set the id_municipio.
	 * 
	 * @param idMunicipio
	 *            id_municipio
	 */
	public void setIdMunicipio(String idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	/**
	 * Get the id_municipio.
	 * 
	 * @return id_municipio
	 */
	public String getIdMunicipio() {
		return this.idMunicipio;
	}

	/**
	 * Set the nombre_municipio.
	 * 
	 * @param nombreMunicipio
	 *            nombre_municipio
	 */
	public void setNombreMunicipio(String nombreMunicipio) {
		this.nombreMunicipio = nombreMunicipio;
	}

	/**
	 * Get the nombre_municipio.
	 * 
	 * @return nombre_municipio
	 */
	public String getNombreMunicipio() {
		return this.nombreMunicipio;
	}

	/**
	 * Set the departamento.
	 * 
	 * @param departamento
	 *            departamento
	 */
	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	/**
	 * Get the departamento.
	 * 
	 * @return departamento
	 */
	public Departamento getDepartamento() {
		return this.departamento;
	}

	/**
	 * Set the set of the paciente.
	 * 
	 * @param pacienteSet
	 *            The set of paciente
	 */
	public void setPacienteSet(Set<Paciente> pacienteSet) {
		this.pacienteSet = pacienteSet;
	}

	/**
	 * Add the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void addPaciente(Paciente paciente) {
		this.pacienteSet.add(paciente);
	}

	/**
	 * Get the set of the paciente.
	 * 
	 * @return The set of paciente
	 */
	public Set<Paciente> getPacienteSet() {
		return this.pacienteSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idMunicipio == null) ? 0 : idMunicipio.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Municipio other = (Municipio) obj;
		if (idMunicipio == null) {
			if (other.idMunicipio != null) {
				return false;
			}
		} else if (!idMunicipio.equals(other.idMunicipio)) {
			return false;
		}
		return true;
	}

}
