package eam.desarrollo.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of proveedor.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Proveedor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_proveedor. */
	private String idProveedor;

	/** nombre_proveedor. */
	private String nombreProveedor;

	/** persona_contacto. */
	private String personaContacto;

	/** direccion_proveedor. */
	private String direccionProveedor;

	/** telefono_proveedor. */
	private String telefonoProveedor;

	/** email_preveedor. */
	private String emailPreveedor;

	/** The set of medicamento_proveedor. */
	private Set<MedicamentoProveedor> medicamentoProveedorSet;

	/**
	 * Constructor.
	 */
	public Proveedor() {
		this.medicamentoProveedorSet = new HashSet<MedicamentoProveedor>();
	}

	/**
	 * Set the id_proveedor.
	 * 
	 * @param idProveedor
	 *            id_proveedor
	 */
	public void setIdProveedor(String idProveedor) {
		this.idProveedor = idProveedor;
	}

	/**
	 * Get the id_proveedor.
	 * 
	 * @return id_proveedor
	 */
	public String getIdProveedor() {
		return this.idProveedor;
	}

	/**
	 * Set the nombre_proveedor.
	 * 
	 * @param nombreProveedor
	 *            nombre_proveedor
	 */
	public void setNombreProveedor(String nombreProveedor) {
		this.nombreProveedor = nombreProveedor;
	}

	/**
	 * Get the nombre_proveedor.
	 * 
	 * @return nombre_proveedor
	 */
	public String getNombreProveedor() {
		return this.nombreProveedor;
	}

	/**
	 * Set the persona_contacto.
	 * 
	 * @param personaContacto
	 *            persona_contacto
	 */
	public void setPersonaContacto(String personaContacto) {
		this.personaContacto = personaContacto;
	}

	/**
	 * Get the persona_contacto.
	 * 
	 * @return persona_contacto
	 */
	public String getPersonaContacto() {
		return this.personaContacto;
	}

	/**
	 * Set the direccion_proveedor.
	 * 
	 * @param direccionProveedor
	 *            direccion_proveedor
	 */
	public void setDireccionProveedor(String direccionProveedor) {
		this.direccionProveedor = direccionProveedor;
	}

	/**
	 * Get the direccion_proveedor.
	 * 
	 * @return direccion_proveedor
	 */
	public String getDireccionProveedor() {
		return this.direccionProveedor;
	}

	/**
	 * Set the telefono_proveedor.
	 * 
	 * @param telefonoProveedor
	 *            telefono_proveedor
	 */
	public void setTelefonoProveedor(String telefonoProveedor) {
		this.telefonoProveedor = telefonoProveedor;
	}

	/**
	 * Get the telefono_proveedor.
	 * 
	 * @return telefono_proveedor
	 */
	public String getTelefonoProveedor() {
		return this.telefonoProveedor;
	}

	/**
	 * Set the email_preveedor.
	 * 
	 * @param emailPreveedor
	 *            email_preveedor
	 */
	public void setEmailPreveedor(String emailPreveedor) {
		this.emailPreveedor = emailPreveedor;
	}

	/**
	 * Get the email_preveedor.
	 * 
	 * @return email_preveedor
	 */
	public String getEmailPreveedor() {
		return this.emailPreveedor;
	}

	/**
	 * Set the set of the medicamento_proveedor.
	 * 
	 * @param medicamentoProveedorSet
	 *            The set of medicamento_proveedor
	 */
	public void setMedicamentoProveedorSet(Set<MedicamentoProveedor> medicamentoProveedorSet) {
		this.medicamentoProveedorSet = medicamentoProveedorSet;
	}

	/**
	 * Add the medicamento_proveedor.
	 * 
	 * @param medicamentoProveedor
	 *            medicamento_proveedor
	 */
	public void addMedicamentoProveedor(MedicamentoProveedor medicamentoProveedor) {
		this.medicamentoProveedorSet.add(medicamentoProveedor);
	}

	/**
	 * Get the set of the medicamento_proveedor.
	 * 
	 * @return The set of medicamento_proveedor
	 */
	public Set<MedicamentoProveedor> getMedicamentoProveedorSet() {
		return this.medicamentoProveedorSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idProveedor == null) ? 0 : idProveedor.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Proveedor other = (Proveedor) obj;
		if (idProveedor == null) {
			if (other.idProveedor != null) {
				return false;
			}
		} else if (!idProveedor.equals(other.idProveedor)) {
			return false;
		}
		return true;
	}

}
