package eam.desarrollo.entidades;

import java.io.Serializable;
import java.sql.Time;
import java.util.Date;

/**
 * Model class of salida_paciente.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SalidaPaciente implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_salida_paciente. */
	private String idSalidaPaciente;

	/** hora_salida_paciente. */
	private Time horaSalidaPaciente;

	/** fecha_salida_paciente. */
	private Date fechaSalidaPaciente;

	/** paciente. */
	private Paciente paciente;

	/**
	 * Constructor.
	 */
	public SalidaPaciente() {
	}

	/**
	 * Set the id_salida_paciente.
	 * 
	 * @param idSalidaPaciente
	 *            id_salida_paciente
	 */
	public void setIdSalidaPaciente(String idSalidaPaciente) {
		this.idSalidaPaciente = idSalidaPaciente;
	}

	/**
	 * Get the id_salida_paciente.
	 * 
	 * @return id_salida_paciente
	 */
	public String getIdSalidaPaciente() {
		return this.idSalidaPaciente;
	}

	/**
	 * Set the hora_salida_paciente.
	 * 
	 * @param horaSalidaPaciente
	 *            hora_salida_paciente
	 */
	public void setHoraSalidaPaciente(Time horaSalidaPaciente) {
		this.horaSalidaPaciente = horaSalidaPaciente;
	}

	/**
	 * Get the hora_salida_paciente.
	 * 
	 * @return hora_salida_paciente
	 */
	public Time getHoraSalidaPaciente() {
		return this.horaSalidaPaciente;
	}

	/**
	 * Set the fecha_salida_paciente.
	 * 
	 * @param fechaSalidaPaciente
	 *            fecha_salida_paciente
	 */
	public void setFechaSalidaPaciente(Date fechaSalidaPaciente) {
		this.fechaSalidaPaciente = fechaSalidaPaciente;
	}

	/**
	 * Get the fecha_salida_paciente.
	 * 
	 * @return fecha_salida_paciente
	 */
	public Date getFechaSalidaPaciente() {
		return this.fechaSalidaPaciente;
	}

	/**
	 * Set the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/**
	 * Get the paciente.
	 * 
	 * @return paciente
	 */
	public Paciente getPaciente() {
		return this.paciente;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSalidaPaciente == null) ? 0 : idSalidaPaciente.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SalidaPaciente other = (SalidaPaciente) obj;
		if (idSalidaPaciente == null) {
			if (other.idSalidaPaciente != null) {
				return false;
			}
		} else if (!idSalidaPaciente.equals(other.idSalidaPaciente)) {
			return false;
		}
		return true;
	}

}
