package eam.desarrollo.entidades;

import java.io.Serializable;
import java.sql.Time;
import java.util.Date;

/**
 * Model class of salida_medico.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SalidaMedico implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_salida_medico. */
	private String idSalidaMedico;

	/** hora_salida_medico. */
	private Time horaSalidaMedico;

	/** fecha_salida_medico. */
	private Date fechaSalidaMedico;

	/** medico. */
	private Medico medico;

	/**
	 * Constructor.
	 */
	public SalidaMedico() {
	}

	/**
	 * Set the id_salida_medico.
	 * 
	 * @param idSalidaMedico
	 *            id_salida_medico
	 */
	public void setIdSalidaMedico(String idSalidaMedico) {
		this.idSalidaMedico = idSalidaMedico;
	}

	/**
	 * Get the id_salida_medico.
	 * 
	 * @return id_salida_medico
	 */
	public String getIdSalidaMedico() {
		return this.idSalidaMedico;
	}

	/**
	 * Set the hora_salida_medico.
	 * 
	 * @param horaSalidaMedico
	 *            hora_salida_medico
	 */
	public void setHoraSalidaMedico(Time horaSalidaMedico) {
		this.horaSalidaMedico = horaSalidaMedico;
	}

	/**
	 * Get the hora_salida_medico.
	 * 
	 * @return hora_salida_medico
	 */
	public Time getHoraSalidaMedico() {
		return this.horaSalidaMedico;
	}

	/**
	 * Set the fecha_salida_medico.
	 * 
	 * @param fechaSalidaMedico
	 *            fecha_salida_medico
	 */
	public void setFechaSalidaMedico(Date fechaSalidaMedico) {
		this.fechaSalidaMedico = fechaSalidaMedico;
	}

	/**
	 * Get the fecha_salida_medico.
	 * 
	 * @return fecha_salida_medico
	 */
	public Date getFechaSalidaMedico() {
		return this.fechaSalidaMedico;
	}

	/**
	 * Set the medico.
	 * 
	 * @param medico
	 *            medico
	 */
	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	/**
	 * Get the medico.
	 * 
	 * @return medico
	 */
	public Medico getMedico() {
		return this.medico;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSalidaMedico == null) ? 0 : idSalidaMedico.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SalidaMedico other = (SalidaMedico) obj;
		if (idSalidaMedico == null) {
			if (other.idSalidaMedico != null) {
				return false;
			}
		} else if (!idSalidaMedico.equals(other.idSalidaMedico)) {
			return false;
		}
		return true;
	}

}
