package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of urgencia_procedimiento.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UrgenciaProcedimiento implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** urgencia. */
	private Urgencia urgencia;

	/** procedimiento. */
	private Procedimiento procedimiento;

	/**
	 * Constructor.
	 */
	public UrgenciaProcedimiento() {
	}

	/**
	 * Set the urgencia.
	 * 
	 * @param urgencia
	 *            urgencia
	 */
	public void setUrgencia(Urgencia urgencia) {
		this.urgencia = urgencia;
	}

	/**
	 * Get the urgencia.
	 * 
	 * @return urgencia
	 */
	public Urgencia getUrgencia() {
		return this.urgencia;
	}

	/**
	 * Set the procedimiento.
	 * 
	 * @param procedimiento
	 *            procedimiento
	 */
	public void setProcedimiento(Procedimiento procedimiento) {
		this.procedimiento = procedimiento;
	}

	/**
	 * Get the procedimiento.
	 * 
	 * @return procedimiento
	 */
	public Procedimiento getProcedimiento() {
		return this.procedimiento;
	}


}
