package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of urgencia_paciente.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UrgenciaPaciente implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** urgencia. */
	private Urgencia urgencia;

	/** paciente. */
	private Paciente paciente;

	/**
	 * Constructor.
	 */
	public UrgenciaPaciente() {
	}

	/**
	 * Set the urgencia.
	 * 
	 * @param urgencia
	 *            urgencia
	 */
	public void setUrgencia(Urgencia urgencia) {
		this.urgencia = urgencia;
	}

	/**
	 * Get the urgencia.
	 * 
	 * @return urgencia
	 */
	public Urgencia getUrgencia() {
		return this.urgencia;
	}

	/**
	 * Set the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/**
	 * Get the paciente.
	 * 
	 * @return paciente
	 */
	public Paciente getPaciente() {
		return this.paciente;
	}


}
