INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (1,'Buenavista',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (2,'Calarca',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (3,'Circasia',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (4,'Cordoba',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (5,'Filandia',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (6,'Genova',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (7,'La Tebaida',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (8,'Montenegro',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (9,'Pijao',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (10,'Quimbaya',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (11,'Salento',1);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (12,'Apia',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (13,'Balboa',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (14,'Belan de Umbria',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (15,'Dos Quebradas',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (16,'Guatica',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (17,'La Celia',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (18,'La Virginia',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (19,'Marsella',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (20,'Mistrato',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (21,'Pereira',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (22,'Pueblo Rico',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (23,'Quinchia',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (24,'Santa Rosa de Cabal',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (25,'Santuario',2);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (26,'Alcala',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (27,'Andalucia',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (28,'Ansermanuevo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (29,'Argelia',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (30,'Bolovar',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (31,'Buenaventura',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (32,'Buga',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (33,'Bugalagrande',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (34,'Caicedonia',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (35,'Calima',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (36,'Candelaria',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (37,'Cartago,',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (38,'Dagua',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (39,'Cali',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (40,'El aguila',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (41,'El Cairo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (42,'El Cerrito',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (43,'El Dovio',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (44,'Florida',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (45,'Ginebra',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (46,'Guacari',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (47,'Jamundi',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (48,'La Cumbre',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (49,'La Union',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (50,'La Victoria',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (51,'Obando',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (52,'Palmira',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (53,'Pradera',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (54,'Restrepo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (55,'Riofrio',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (56,'Roldanillo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (57,'San Pedro',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (58,'Sevilla',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (59,'Toro',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (60,'Trujillo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (61,'Tulua',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (62,'Ulloa',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (63,'Versalles',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (64,'Vijes',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (65,'Yotoco',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (66,'Yumbo',3);
INSERT INTO municipio(id_municipio,nombre_municipio,id_departamento) VALUES (67,'Zarzal',3);
