package eam.desarrollo.hospital.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of cama.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Cama implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_cama. */
	private String idCama;

	/** estado_cama. */
	private EstadoCama estadoCama;

	/** The set of habitacion. */
	private Set<Habitacion> habitacionSet;

	/**
	 * Constructor.
	 */
	public Cama() {
		this.habitacionSet = new HashSet<Habitacion>();
	}

	/**
	 * Set the id_cama.
	 * 
	 * @param idCama
	 *            id_cama
	 */
	public void setIdCama(String idCama) {
		this.idCama = idCama;
	}

	/**
	 * Get the id_cama.
	 * 
	 * @return id_cama
	 */
	public String getIdCama() {
		return this.idCama;
	}

	/**
	 * Set the estado_cama.
	 * 
	 * @param estadoCama
	 *            estado_cama
	 */
	public void setEstadoCama(EstadoCama estadoCama) {
		this.estadoCama = estadoCama;
	}

	/**
	 * Get the estado_cama.
	 * 
	 * @return estado_cama
	 */
	public EstadoCama getEstadoCama() {
		return this.estadoCama;
	}

	/**
	 * Set the set of the habitacion.
	 * 
	 * @param habitacionSet
	 *            The set of habitacion
	 */
	public void setHabitacionSet(Set<Habitacion> habitacionSet) {
		this.habitacionSet = habitacionSet;
	}

	/**
	 * Add the habitacion.
	 * 
	 * @param habitacion
	 *            habitacion
	 */
	public void addHabitacion(Habitacion habitacion) {
		this.habitacionSet.add(habitacion);
	}

	/**
	 * Get the set of the habitacion.
	 * 
	 * @return The set of habitacion
	 */
	public Set<Habitacion> getHabitacionSet() {
		return this.habitacionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idCama == null) ? 0 : idCama.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Cama other = (Cama) obj;
		if (idCama == null) {
			if (other.idCama != null) {
				return false;
			}
		} else if (!idCama.equals(other.idCama)) {
			return false;
		}
		return true;
	}

}
