package eam.desarrollo.hospital.entidades;

import java.io.Serializable;

/**
 * Model class of diagnostico.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Diagnostico implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_diagnostico. */
	private String idDiagnostico;

	/** nombre_diagnostico. */
	private String nombreDiagnostico;

	/** descripcion_diagnostico. */
	private String descripcionDiagnostico;

	/** medico. */
	private Medico medico;
	private Paciente paciente;

	/**
	 * Constructor.
	 */
	public Diagnostico(String idDiagnostico, String nombreDiagnostico, String descripcionDiagnostico, Medico medico,
			Paciente paciente) {
		super();
		this.idDiagnostico = idDiagnostico;
		this.nombreDiagnostico = nombreDiagnostico;
		this.descripcionDiagnostico = descripcionDiagnostico;
		this.medico = medico;
		this.paciente = paciente;
	}

	/**
	 * Set the id_diagnostico.
	 * 
	 * @param idDiagnostico
	 *            id_diagnostico
	 */
	public void setIdDiagnostico(String idDiagnostico) {
		this.idDiagnostico = idDiagnostico;
	}



	/**
	 * Get the id_diagnostico.
	 * 
	 * @return id_diagnostico
	 */
	public String getIdDiagnostico() {
		return this.idDiagnostico;
	}

	/**
	 * Set the nombre_diagnostico.
	 * 
	 * @param nombreDiagnostico
	 *            nombre_diagnostico
	 */
	public void setNombreDiagnostico(String nombreDiagnostico) {
		this.nombreDiagnostico = nombreDiagnostico;
	}

	/**
	 * Get the nombre_diagnostico.
	 * 
	 * @return nombre_diagnostico
	 */
	public String getNombreDiagnostico() {
		return this.nombreDiagnostico;
	}

	/**
	 * Set the descripcion_diagnostico.
	 * 
	 * @param descripcionDiagnostico
	 *            descripcion_diagnostico
	 */
	public void setDescripcionDiagnostico(String descripcionDiagnostico) {
		this.descripcionDiagnostico = descripcionDiagnostico;
	}

	/**
	 * Get the descripcion_diagnostico.
	 * 
	 * @return descripcion_diagnostico
	 */
	public String getDescripcionDiagnostico() {
		return this.descripcionDiagnostico;
	}

	/**
	 * Set the medico.
	 * 
	 * @param medico
	 *            medico
	 */
	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	/**
	 * Get the medico.
	 * 
	 * @return medico
	 */
	public Medico getMedico() {
		return this.medico;
	}
	
	

	public Paciente getPaciente() {
		return paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idDiagnostico == null) ? 0 : idDiagnostico.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Diagnostico other = (Diagnostico) obj;
		if (idDiagnostico == null) {
			if (other.idDiagnostico != null) {
				return false;
			}
		} else if (!idDiagnostico.equals(other.idDiagnostico)) {
			return false;
		}
		return true;
	}

}
