package eam.desarrollo.hospital.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of estado_cita.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EstadoCita implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_estado_cita. */
	private String idEstadoCita;

	/** descripcion_estado_cita. */
	private String descripcionEstadoCita;

	/** The set of cita. */
	private Set<Cita> citaSet;

	/**
	 * Constructor.
	 */
	public EstadoCita() {
		this.citaSet = new HashSet<Cita>();
	}
	
	
	/**
	 * 
	 * @param idEstadoCita
	 * @param descripcionEstadoCita
	 */
	public EstadoCita(String idEstadoCita, String descripcionEstadoCita) {
		super();
		this.idEstadoCita = idEstadoCita;
		this.descripcionEstadoCita = descripcionEstadoCita;
	}



	/**
	 * Set the id_estado_cita.
	 * 
	 * @param idEstadoCita
	 *            id_estado_cita
	 */
	public void setIdEstadoCita(String idEstadoCita) {
		this.idEstadoCita = idEstadoCita;
	}

	/**
	 * Get the id_estado_cita.
	 * 
	 * @return id_estado_cita
	 */
	public String getIdEstadoCita() {
		return this.idEstadoCita;
	}

	/**
	 * Set the descripcion_estado_cita.
	 * 
	 * @param descripcionEstadoCita
	 *            descripcion_estado_cita
	 */
	public void setDescripcionEstadoCita(String descripcionEstadoCita) {
		this.descripcionEstadoCita = descripcionEstadoCita;
	}

	/**
	 * Get the descripcion_estado_cita.
	 * 
	 * @return descripcion_estado_cita
	 */
	public String getDescripcionEstadoCita() {
		return this.descripcionEstadoCita;
	}

	/**
	 * Set the set of the cita.
	 * 
	 * @param citaSet
	 *            The set of cita
	 */
	public void setCitaSet(Set<Cita> citaSet) {
		this.citaSet = citaSet;
	}

	/**
	 * Add the cita.
	 * 
	 * @param cita
	 *            cita
	 */
	public void addCita(Cita cita) {
		this.citaSet.add(cita);
	}

	/**
	 * Get the set of the cita.
	 * 
	 * @return The set of cita
	 */
	public Set<Cita> getCitaSet() {
		return this.citaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEstadoCita == null) ? 0 : idEstadoCita.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EstadoCita other = (EstadoCita) obj;
		if (idEstadoCita == null) {
			if (other.idEstadoCita != null) {
				return false;
			}
		} else if (!idEstadoCita.equals(other.idEstadoCita)) {
			return false;
		}
		return true;
	}


	@Override
	public String toString() {
		return descripcionEstadoCita;
	}
	 
	

}
