package eam.desarrollo.hospital.entidades;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of farmacia.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Farmacia implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_farmacia. */
	private String idFarmacia;
	private String nombreFarmacia;
	private String personaACargo;
	private String telefonoFarmacia;

	

	

	
	public Farmacia(String idFarmacia, String nombreFarmacia, String personaACargo, String telefonoFarmacia) {
		super();
		this.idFarmacia = idFarmacia;
		this.nombreFarmacia = nombreFarmacia;
		this.personaACargo = personaACargo;
		this.telefonoFarmacia = telefonoFarmacia;
	}
	
	
	/** The set of medicamento. */
	/**private Set<Medicamento> medicamentoSet;
	**/
	public String getIdFarmacia() {
		return idFarmacia;
	}

	public void setIdFarmacia(String idFarmacia) {
		this.idFarmacia = idFarmacia;
	}

	public String getNombreFarmacia() {
		return nombreFarmacia;
	}

	public void setNombreFarmacia(String nombreFarmacia) {
		this.nombreFarmacia = nombreFarmacia;
	}

	public String getPersonaACargo() {
		return personaACargo;
	}

	public void setPersonaACargo(String personaACargo) {
		this.personaACargo = personaACargo;
	}

	public String getTelefonoFarmacia() {
		return telefonoFarmacia;
	}

	public void setTelefonoFarmacia(String telefonoFarmacia) {
		this.telefonoFarmacia = telefonoFarmacia;
	}

	/**
	 * Set the set of the medicamento.
	 * 
	 * @param medicamentoSet
	 *            The set of medicamento
	 */
	/**public void setMedicamentoSet(Set<Medicamento> medicamentoSet) {
		this.medicamentoSet = medicamentoSet;
	}

	/**
	 * Add the medicamento.
	 * 
	 * @param medicamento
	 *            medicamento
	 */
	/**
	public void addMedicamento(Medicamento medicamento) {
		this.medicamentoSet.add(medicamento);
	}

	/**
	 * Get the set of the medicamento.
	 * 
	 * @return The set of medicamento
	 */
	/**
	public Set<Medicamento> getMedicamentoSet() {
		return this.medicamentoSet;
	}
	
	**/
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idFarmacia == null) ? 0 : idFarmacia.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Farmacia other = (Farmacia) obj;
		if (idFarmacia == null) {
			if (other.idFarmacia != null) {
				return false;
			}
		} else if (!idFarmacia.equals(other.idFarmacia)) {
			return false;
		}
		return true;
	}

}
