package eam.desarrollo.entidades;

import java.io.Serializable;

/**
 * Model class of formula_medicamento.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FormulaMedicamento implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private String idFormulaMedicamento;
	/** cantidad_medicamento_formula. */
	private Integer cantidadMedicamentoFormula;
	private String descripcionFormula;
	/** formula. */
	private Formula formula;

	/** medicamento. */
	private Medicamento medicamento;



	/**
	 * Constructor.
	 */
	public FormulaMedicamento(String idFormulaMedicamento, Integer cantidadMedicamentoFormula,
			String descripcionFormula, Formula formula, Medicamento medicamento) {
		super();
		this.idFormulaMedicamento = idFormulaMedicamento;
		this.cantidadMedicamentoFormula = cantidadMedicamentoFormula;
		this.descripcionFormula = descripcionFormula;
		this.formula = formula;
		this.medicamento = medicamento;
	}



	public String getIdFormulaMedicamento() {
		return idFormulaMedicamento;
	}



	public void setIdFormulaMedicamento(String idFormulaMedicamento) {
		this.idFormulaMedicamento = idFormulaMedicamento;
	}



	public Integer getCantidadMedicamentoFormula() {
		return cantidadMedicamentoFormula;
	}



	public void setCantidadMedicamentoFormula(Integer cantidadMedicamentoFormula) {
		this.cantidadMedicamentoFormula = cantidadMedicamentoFormula;
	}



	public String getDescripcionFormula() {
		return descripcionFormula;
	}



	public void setDescripcionFormula(String descripcionFormula) {
		this.descripcionFormula = descripcionFormula;
	}



	public Formula getFormula() {
		return formula;
	}



	public void setFormula(Formula formula) {
		this.formula = formula;
	}



	public Medicamento getMedicamento() {
		return medicamento;
	}



	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}


	

}
