package eam.desarrollo.hospital.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of formula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Formula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private String idFormula;
	private Date fechaFormula;
	private Medico medico;
	private Paciente paciente;
	
	

	public Formula(String idFormula, Date fechaFormula, Medico medico, Paciente paciente) {
		super();
		this.idFormula = idFormula;
		this.fechaFormula = fechaFormula;
		this.medico = medico;
		this.paciente = paciente;
	}

	public String getIdFormula() {
		return idFormula;
	}

	public void setIdFormula(String idFormula) {
		this.idFormula = idFormula;
	}

	public Date getFechaFormula() {
		return fechaFormula;
	}

	public void setFechaFormula(Date fechaFormula) {
		this.fechaFormula = fechaFormula;
	}

	public Medico getMedico() {
		return medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	public Paciente getPaciente() {
		return paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}
	
	

	


	
	

}
