package eam.desarrollo.hospital.entidades;

import java.io.Serializable;

/**
 * Model class of habitacion.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Habitacion implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_habitacion. */
	private String idHabitacion;

	/** cantidad_camas. */
	private Integer cantidadCamas;

	/** consultorio. */
	private Consultorio consultorio;

	/** cama. */
	private Cama cama;

	/**
	 * Constructor.
	 */
	public Habitacion() {
	}

	/**
	 * Set the id_habitacion.
	 * 
	 * @param idHabitacion
	 *            id_habitacion
	 */
	public void setIdHabitacion(String idHabitacion) {
		this.idHabitacion = idHabitacion;
	}

	/**
	 * Get the id_habitacion.
	 * 
	 * @return id_habitacion
	 */
	public String getIdHabitacion() {
		return this.idHabitacion;
	}

	/**
	 * Set the cantidad_camas.
	 * 
	 * @param cantidadCamas
	 *            cantidad_camas
	 */
	public void setCantidadCamas(Integer cantidadCamas) {
		this.cantidadCamas = cantidadCamas;
	}

	/**
	 * Get the cantidad_camas.
	 * 
	 * @return cantidad_camas
	 */
	public Integer getCantidadCamas() {
		return this.cantidadCamas;
	}

	/**
	 * Set the consultorio.
	 * 
	 * @param consultorio
	 *            consultorio
	 */
	public void setConsultorio(Consultorio consultorio) {
		this.consultorio = consultorio;
	}

	/**
	 * Get the consultorio.
	 * 
	 * @return consultorio
	 */
	public Consultorio getConsultorio() {
		return this.consultorio;
	}

	/**
	 * Set the cama.
	 * 
	 * @param cama
	 *            cama
	 */
	public void setCama(Cama cama) {
		this.cama = cama;
	}

	/**
	 * Get the cama.
	 * 
	 * @return cama
	 */
	public Cama getCama() {
		return this.cama;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idHabitacion == null) ? 0 : idHabitacion.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Habitacion other = (Habitacion) obj;
		if (idHabitacion == null) {
			if (other.idHabitacion != null) {
				return false;
			}
		} else if (!idHabitacion.equals(other.idHabitacion)) {
			return false;
		}
		return true;
	}

}
