package eam.desarrollo.hospital.entidades;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of paciente.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Paciente implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_paciente. */
	private String idPaciente;

	/** nombre_paciente. */
	private String nombrePaciente;

	/** apellido_paciente. */
	private String apellidoPaciente;

	/** direccion_paciente. */
	private String direccionPaciente;

	/** fecha_nacimiento_paciente. */
	private Date fechaNacimientoPaciente;

	/** telefono_paciente. */
	private String telefonoPaciente;

	/** peso_paciente. */
	private Float pesoPaciente;

	/** numero_documento_paciente. */
	private String numeroDocumentoPaciente;

	/** tipodocumento. */
	private Tipodocumento tipodocumento;

	/** municipio. */
	private Municipio municipio;

	/** genero. */
	private Genero genero;

	/** The set of cita. */
	private Set<Cita> citaSet;

	/** The set of historia_paciente. */
	private Set<HistoriaPaciente> historiaPacienteSet;

	/** The set of remision. */
	private Set<Remision> remisionSet;

	/** The set of urgencia_paciente. */
	//private Set<UrgenciaPaciente> urgenciaPacienteSet;

	
	/**
	 * Constructor.
	 */
	public Paciente() {
		this.citaSet = new HashSet<Cita>();
		this.historiaPacienteSet = new HashSet<HistoriaPaciente>();
		this.remisionSet = new HashSet<Remision>();
		//this.urgenciaPacienteSet = new HashSet<UrgenciaPaciente>();
	}

	/**
	 * 
	 * @param idPaciente
	 * @param nombrePaciente
	 * @param apellidoPaciente
	 * @param direccionPaciente
	 * @param fechaNacimientoPaciente
	 * @param telefonoPaciente
	 * @param pesoPaciente
	 * @param numeroDocumentoPaciente
	 * @param tipodocumento
	 * @param municipio
	 * @param genero
	 * @param citaSet
	 * @param historiaPacienteSet
	 * @param remisionSet
	 */
	public Paciente(String idPaciente, String nombrePaciente, String apellidoPaciente, String direccionPaciente,
			Date fechaNacimientoPaciente, String telefonoPaciente, Float pesoPaciente, String numeroDocumentoPaciente,
			Tipodocumento tipodocumento, Municipio municipio, Genero genero) {
		super();
		this.idPaciente = idPaciente;
		this.nombrePaciente = nombrePaciente;
		this.apellidoPaciente = apellidoPaciente;
		this.direccionPaciente = direccionPaciente;
		this.fechaNacimientoPaciente = fechaNacimientoPaciente;
		this.telefonoPaciente = telefonoPaciente;
		this.pesoPaciente = pesoPaciente;
		this.numeroDocumentoPaciente = numeroDocumentoPaciente;
		this.tipodocumento = tipodocumento;
		this.municipio = municipio;
		this.genero = genero;
	}

	/**
	 * Set the id_paciente.
	 * 
	 * @param idPaciente
	 *            id_paciente
	 */
	public void setIdPaciente(String idPaciente) {
		this.idPaciente = idPaciente;
	}

	/**
	 * Get the id_paciente.
	 * 
	 * @return id_paciente
	 */
	public String getIdPaciente() {
		return this.idPaciente;
	}

	/**
	 * Set the nombre_paciente.
	 * 
	 * @param nombrePaciente
	 *            nombre_paciente
	 */
	public void setNombrePaciente(String nombrePaciente) {
		this.nombrePaciente = nombrePaciente;
	}

	/**
	 * Get the nombre_paciente.
	 * 
	 * @return nombre_paciente
	 */
	public String getNombrePaciente() {
		return this.nombrePaciente;
	}

	/**
	 * Set the apellido_paciente.
	 * 
	 * @param apellidoPaciente
	 *            apellido_paciente
	 */
	public void setApellidoPaciente(String apellidoPaciente) {
		this.apellidoPaciente = apellidoPaciente;
	}

	/**
	 * Get the apellido_paciente.
	 * 
	 * @return apellido_paciente
	 */
	public String getApellidoPaciente() {
		return this.apellidoPaciente;
	}

	/**
	 * Set the direccion_paciente.
	 * 
	 * @param direccionPaciente
	 *            direccion_paciente
	 */
	public void setDireccionPaciente(String direccionPaciente) {
		this.direccionPaciente = direccionPaciente;
	}

	/**
	 * Get the direccion_paciente.
	 * 
	 * @return direccion_paciente
	 */
	public String getDireccionPaciente() {
		return this.direccionPaciente;
	}

	/**
	 * Set the fecha_nacimiento_paciente.
	 * 
	 * @param fechaNacimientoPaciente
	 *            fecha_nacimiento_paciente
	 */
	public void setFechaNacimientoPaciente(Date fechaNacimientoPaciente) {
		this.fechaNacimientoPaciente = fechaNacimientoPaciente;
	}

	/**
	 * Get the fecha_nacimiento_paciente.
	 * 
	 * @return fecha_nacimiento_paciente
	 */
	public Date getFechaNacimientoPaciente() {
		return this.fechaNacimientoPaciente;
	}

	/**
	 * Set the telefono_paciente.
	 * 
	 * @param telefonoPaciente
	 *            telefono_paciente
	 */
	public void setTelefonoPaciente(String telefonoPaciente) {
		this.telefonoPaciente = telefonoPaciente;
	}

	/**
	 * Get the telefono_paciente.
	 * 
	 * @return telefono_paciente
	 */
	public String getTelefonoPaciente() {
		return this.telefonoPaciente;
	}

	/**
	 * Set the peso_paciente.
	 * 
	 * @param pesoPaciente
	 *            peso_paciente
	 */
	public void setPesoPaciente(Float pesoPaciente) {
		this.pesoPaciente = pesoPaciente;
	}

	/**
	 * Get the peso_paciente.
	 * 
	 * @return peso_paciente
	 */
	public Float getPesoPaciente() {
		return this.pesoPaciente;
	}

	/**
	 * Set the numero_documento_paciente.
	 * 
	 * @param numeroDocumentoPaciente
	 *            numero_documento_paciente
	 */
	public void setNumeroDocumentoPaciente(String numeroDocumentoPaciente) {
		this.numeroDocumentoPaciente = numeroDocumentoPaciente;
	}

	/**
	 * Get the numero_documento_paciente.
	 * 
	 * @return numero_documento_paciente
	 */
	public String getNumeroDocumentoPaciente() {
		return this.numeroDocumentoPaciente;
	}

	/**
	 * Set the tipodocumento.
	 * 
	 * @param tipodocumento
	 *            tipodocumento
	 */
	public void setTipodocumento(Tipodocumento tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	/**
	 * Get the tipodocumento.
	 * 
	 * @return tipodocumento
	 */
	public Tipodocumento getTipodocumento() {
		return this.tipodocumento;
	}

	/**
	 * Set the municipio.
	 * 
	 * @param municipio
	 *            municipio
	 */
	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	/**
	 * Get the municipio.
	 * 
	 * @return municipio
	 */
	public Municipio getMunicipio() {
		return this.municipio;
	}

	/**
	 * Set the genero.
	 * 
	 * @param genero
	 *            genero
	 */
	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	/**
	 * Get the genero.
	 * 
	 * @return genero
	 */
	public Genero getGenero() {
		return this.genero;
	}

	/**
	 * Set the set of the cita.
	 * 
	 * @param citaSet
	 *            The set of cita
	 */
	public void setCitaSet(Set<Cita> citaSet) {
		this.citaSet = citaSet;
	}

	/**
	 * Add the cita.
	 * 
	 * @param cita
	 *            cita
	 */
	public void addCita(Cita cita) {
		this.citaSet.add(cita);
	}

	/**
	 * Get the set of the cita.
	 * 
	 * @return The set of cita
	 */
	public Set<Cita> getCitaSet() {
		return this.citaSet;
	}

	/**
	 * Set the set of the historia_paciente.
	 * 
	 * @param historiaPacienteSet
	 *            The set of historia_paciente
	 */
	public void setHistoriaPacienteSet(Set<HistoriaPaciente> historiaPacienteSet) {
		this.historiaPacienteSet = historiaPacienteSet;
	}

	/**
	 * Add the historia_paciente.
	 * 
	 * @param historiaPaciente
	 *            historia_paciente
	 */
	public void addHistoriaPaciente(HistoriaPaciente historiaPaciente) {
		this.historiaPacienteSet.add(historiaPaciente);
	}

	/**
	 * Get the set of the historia_paciente.
	 * 
	 * @return The set of historia_paciente
	 */
	public Set<HistoriaPaciente> getHistoriaPacienteSet() {
		return this.historiaPacienteSet;
	}

	/**
	 * Set the set of the remision.
	 * 
	 * @param remisionSet
	 *            The set of remision
	 */
	public void setRemisionSet(Set<Remision> remisionSet) {
		this.remisionSet = remisionSet;
	}

	/**
	 * Add the remision.
	 * 
	 * @param remision
	 *            remision
	 */
	public void addRemision(Remision remision) {
		this.remisionSet.add(remision);
	}

	/**
	 * Get the set of the remision.
	 * 
	 * @return The set of remision
	 */
	public Set<Remision> getRemisionSet() {
		return this.remisionSet;
	}

	/**
	 * Set the set of the urgencia_paciente.
	 * 
	 * @param urgenciaPacienteSet
	 *            The set of urgencia_paciente
	 */
	/*public void setUrgenciaPacienteSet(Set<UrgenciaPaciente> urgenciaPacienteSet) {
		//this.urgenciaPacienteSet = urgenciaPacienteSet;
	}*/

	/**
	 * Add the urgencia_paciente.
	 * 
	 * @param urgenciaPaciente
	 *            urgencia_paciente
	 */
	/*public void addUrgenciaPaciente(UrgenciaPaciente urgenciaPaciente) {
		//this.urgenciaPacienteSet.add(urgenciaPaciente);
	}*/

	/**
	 * Get the set of the urgencia_paciente.
	 * 
	 * @return The set of urgencia_paciente
	 */
	/*public Set<UrgenciaPaciente> getUrgenciaPacienteSet() {
		return this.urgenciaPacienteSet;
	}*/

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idPaciente == null) ? 0 : idPaciente.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Paciente other = (Paciente) obj;
		if (idPaciente == null) {
			if (other.idPaciente != null) {
				return false;
			}
		} else if (!idPaciente.equals(other.idPaciente)) {
			return false;
		}
		return true;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Paciente [idPaciente=" + idPaciente + ", nombrePaciente=" + nombrePaciente + ", apellidoPaciente="
				+ apellidoPaciente + ", direccionPaciente=" + direccionPaciente + ", fechaNacimientoPaciente="
				+ fechaNacimientoPaciente + ", telefonoPaciente=" + telefonoPaciente + ", pesoPaciente=" + pesoPaciente
				+ ", numeroDocumentoPaciente=" + numeroDocumentoPaciente + ", tipodocumento=" + tipodocumento
				+ ", municipio=" + municipio + ", genero=" + genero + "]";
	}
	
	

}
