package eam.desarrollo.hospital.entidades;
import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Profesional.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Profesional implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** IdProfesional. */
	private Integer idprofesional;

	/** nombre_profesional. */
	private String nombreProfesional;

	/** apellido_profesional. */
	private String apellidoProfesional;

	/** identificacion_profesional. */
	private Integer identificacionProfesional;

	/** area_profesional. */
	private String areaProfesional;

	/** telefono_profesional. */
	private String telefonoProfesional;

	/** direccion_profesional. */
	private String direccionProfesional;

	

	
	/**
	 * 
	 * @param idprofesional
	 * @param nombreProfesional
	 * @param apellidoProfesional
	 * @param identificacionProfesional
	 * @param areaProfesional
	 * @param telefonoProfesional
	 * @param direccionProfesional
	 * @param diasdisponibles
	 * @param horariodisponible
	 */
	public Profesional(Integer idprofesional, String nombreProfesional, String apellidoProfesional,
			Integer identificacionProfesional, String areaProfesional, String telefonoProfesional,
			String direccionProfesional) {
		super();
		this.idprofesional = idprofesional;
		this.nombreProfesional = nombreProfesional;
		this.apellidoProfesional = apellidoProfesional;
		this.identificacionProfesional = identificacionProfesional;
		this.areaProfesional = areaProfesional;
		this.telefonoProfesional = telefonoProfesional;
		this.direccionProfesional = direccionProfesional;
	}




	public Integer getIdprofesional() {
		return idprofesional;
	}




	public void setIdprofesional(Integer idprofesional) {
		this.idprofesional = idprofesional;
	}




	public String getNombreProfesional() {
		return nombreProfesional;
	}




	public void setNombreProfesional(String nombreProfesional) {
		this.nombreProfesional = nombreProfesional;
	}




	public String getApellidoProfesional() {
		return apellidoProfesional;
	}




	public void setApellidoProfesional(String apellidoProfesional) {
		this.apellidoProfesional = apellidoProfesional;
	}




	public Integer getIdentificacionProfesional() {
		return identificacionProfesional;
	}




	public void setIdentificacionProfesional(Integer identificacionProfesional) {
		this.identificacionProfesional = identificacionProfesional;
	}




	public String getAreaProfesional() {
		return areaProfesional;
	}




	public void setAreaProfesional(String areaProfesional) {
		this.areaProfesional = areaProfesional;
	}




	public String getTelefonoProfesional() {
		return telefonoProfesional;
	}




	public void setTelefonoProfesional(String telefonoProfesional) {
		this.telefonoProfesional = telefonoProfesional;
	}




	public String getDireccionProfesional() {
		return direccionProfesional;
	}




	public void setDireccionProfesional(String direccionProfesional) {
		this.direccionProfesional = direccionProfesional;
	}



}
