package eam.desarrollo.hospital.entidades;

import java.io.Serializable;

/**
 * Model class of remision.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Remision implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id_remision. */
	private String idRemision;

	/** paciente. */
	private Paciente paciente;

	/** descripcion_remision. */
	private String descripcionRemision;

	/**
	 * Constructor.
	 */
	public Remision() {
	}

	/**
	 * Set the id_remision.
	 * 
	 * @param idRemision
	 *            id_remision
	 */
	public void setIdRemision(String idRemision) {
		this.idRemision = idRemision;
	}

	/**
	 * Get the id_remision.
	 * 
	 * @return id_remision
	 */
	public String getIdRemision() {
		return this.idRemision;
	}

	/**
	 * Set the paciente.
	 * 
	 * @param paciente
	 *            paciente
	 */
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/**
	 * Get the paciente.
	 * 
	 * @return paciente
	 */
	public Paciente getPaciente() {
		return this.paciente;
	}

	/**
	 * Set the descripcion_remision.
	 * 
	 * @param descripcionRemision
	 *            descripcion_remision
	 */
	public void setDescripcionRemision(String descripcionRemision) {
		this.descripcionRemision = descripcionRemision;
	}

	/**
	 * Get the descripcion_remision.
	 * 
	 * @return descripcion_remision
	 */
	public String getDescripcionRemision() {
		return this.descripcionRemision;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idRemision == null) ? 0 : idRemision.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Remision other = (Remision) obj;
		if (idRemision == null) {
			if (other.idRemision != null) {
				return false;
			}
		} else if (!idRemision.equals(other.idRemision)) {
			return false;
		}
		return true;
	}

}
